config/routes.rb
Terminplaner::Application.routes.draw do

  resources :groups
  resources :user_sessions
  resources :users
  resources :user, :as => :friend
  resources :application
  resources :appointments
  resources :appointments, :collection => {:with_code => :get}
  resources :friendships
  resources :friendship_appointments
  resources :password_resets

  match 'signup' => 'users#new', :as => :signup
  match 'appointments#index' => "application", :action=>"set_layout", :mobile=>"1"
  match 'appointments#index' => "application", :action=>"set_layout", :mobile=>"0"
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout

  match 'appointments#index' => "application", :action=>"groups#edit"

  match ':controller(/:id(.:format)(/:action))'
  match ':controller(/:action(/:id(.:format)))'
  match ':controller(/:action(.:format))'
  match 'activate(/:activation_code)' => 'users#activate', :as => :activate_account
  match 'send_activation(/:user_id)' => 'users#send_activation', :as => :send_activation
  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  get "home/index"

  root :to => 'appointments#index'

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :appointments
  has_many :groups,     :through => :appointments

  has_many :friends, :through => :friendships, :conditions => "status = 'accepted'"
  has_many :appointments,:through =>:friendships, :source => :friend, :conditions => "selected = 'true'"
    #has_many :appointments,:through =>:friends

  has_many :requested_friends, :through => :friendships, :source => :friend, :conditions => "status = 'requested'", :order => :created_at
  has_many :pending_friends, :through => :friendships, :source => :friend, :conditions => "status = 'pending'", :order => :created_at
  has_many :friendships, :dependent => :destroy

  #next try
  has_many :shared_friends, :through => :friendship_appointments
  has_many :appointments,:through =>:friendship_appointments, :source => :shared_friends
  has_many :friendship_appointments, :dependent => :destroy



  acts_as_authentic do |c|
    #	Add	custom	conﬁgura'on	op'ons	here
    #config.crypto_provider = Authlogic::CryptoProviders::MD5
  end

  def self.find_by_login_or_email(login)
   find_by_login(login) || find_by_email(login)
  end

  def admin?
    return admin || (id == 1)
  end

  def active?
    return active  || (id == 1)
  end

  def activate!
    self.active = true
    save
  end

  def deactivate!
    self.active = false
    save
  end

  def send_activation_instructions!
    reset_perishable_token!
    Notifier.activation_instructions(self).deliver
  end

  def send_activation_confirmation!
    reset_perishable_token!
    Notifier.activation_confirmation(self).deliver
  end

  def email_address_with_name
    #TODO  Alle Adressen werden zur RUBY Test adresse geschickt,
    # ehemaliger befehl:
    #"#{self.login}  <#{self.email}>"
    "#{self.login} <#{"rubyprojekt@googlemail.com"}>" #
  end

  def deliver_password_reset_instructions!
    reset_perishable_token!
    Notifier.password_reset_instructions(self).deliver
  end

  def create_no_group
    gr = Group.create \
                  :name => 'No Group',
                  :description => '',
                  :colour => '#ffffff',
                  :user_id => self.id
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :require_no_user, :only => [:new, :create]
  #before_filter :require_user, :only => [:index, :edit, :update ,:show]
  before_filter :require_admin    ,:only =>   [:index]




  # GET /users
  # GET /users.json
  def index
    @group = Group.new
    @groups = Group.find(:all, :conditions => {:user_id => current_user})

    @users = User.all
    @user = current_user

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @group = Group.new
    @groups = Group.find(:all, :conditions => {:user_id => current_user})

    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @group = Group.new
    @groups = Group.find(:all, :conditions => {:user_id => current_user})
    @user = User.find(params[:id])

  end

  # POST /users
    # POST /users.json
  # new create method:
  def create
    @user = User.new(params[:user])

    # Saving without session maintenance to skip
    # auto-login which can't happen here because
    # the User has not yet been activated
    if @user.save_without_session_maintenance
      @user.send_activation_instructions!      # new method in the User model

      @user.create_no_group
      flash[:notice] = "Please confirm your account by following the instructions we've sent to your " + @user.email + " email address."
      redirect_to new_user_session_url
    else

    end
  end

  def activate
    @user = User.find_using_perishable_token(params[:activation_code], 1.week) || (raise Exception)

    raise Exception if @user.active?

    if @user.activate!
      UserSession.create(@user)#UserSession.create(@user, false)
      @user.send_activation_confirmation!
      flash[:notice] = "Your account has been activated."
      redirect_to root_url
    else

      render :action => :new
    end
  end



  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to appointments_path, notice: 'User was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :ok }
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/users/_edituser.html.erb
<%= form_for(meinevariable) do |f| %>


   <label class="label" >Username</label>
    <%= f.text_field :login, :class=>"textarea" %>

   <label class="label" >Email</label>
    <%= f.text_field :email, :class=>"textarea" %>

    <label class="label" >Password</label>
    <%= f.password_field :password, :class=>"textarea" %>

      <label class="label" >Password (confirm)</label>
      <%= f.password_field :password_confirmation, :class=>"textarea" %>
    <span class="floatright">
    <%= f.submit '', :class=> 'button create', :title=>'Save Account' %>
    </span>

<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>

  <div class="field">
   <label class="label" >Username</label>
    <%= f.text_field :login, :class=>"textarea" %>

   <label class="label" >Email</label>
    <%= f.text_field :email, :class=>"textarea" %>

    <!-- ADMINFIELD  -->
    <% if current_user %>

           <% if current_user.admin? %>
               <label class="label" >Admin</label>

                <%=  f.text_field :admin, :class=>"textarea" %>

               <label class="label" >Activated</label>

                <%=  f.text_field :active, :class=>"textarea" %>

          <% end %>

    <% end %>
     <!-- Adminfield ende -->

    <label class="label" >Password</label>
    <%= f.password_field :password, :class=>"textarea" %>

      <label class="label" >Password (confirm)</label>
      <%= f.password_field :password_confirmation, :class=>"textarea" %>
    <span class="floatright">

    <%= f.submit '', :class=> 'button save', :title=>'Create new Account' %>
    </span>
  </div>
<% end %>

app/views/users/edit.html.erb
    <h1>Edit <%= current_user.login %>'s Account</h1>

  <%= render 'form' %>

app/views/users/index.html.erb
<h1>Users List</h1>


<p id="notice"><%= notice %></p>
<table class ="pretty">
  <thead>

    <th>Username</th>
    <!--ADMINFIELD-->
    <% if current_user %>
        <% if current_user.admin? %>
            <th>User-ID</th>
            <th>Email</th>
            <th>Admin</th>
            <th>Activated</th>
            <th>Last Login</th>
        <% end %>
    <% end %>


    <th></th>
    <th></th>
  </thead>

<% @users.each do |user| %>
  <tbody>

    <% # comments %>

    <td><%= user.login %></td>


     <!--ADMINFIELD-->
    <% if current_user %>
        <% if current_user.admin? %>
            <td><%= user.id %></td>
            <td><%= user.email %></td>
            <td><%= user.admin? %></td>
            <td><%= user.active? %></td>
            <td><% if user.last_login_at.eql?(nil) %><%= 'not yet'%>
                <% else %><%= user.last_login_at.strftime('%d. %m. %Y') %>
                <% end %></td>
            <td><%= link_to '', edit_user_path(user), class: 'button left edit', title: 'Edit User' %>
            <%= link_to '', user, confirm: 'Are you sure?', method: :delete, class: 'button right delete', title: 'Delete User' %></td>

        <% end %>
    <% end %>

     <!-- Adminfield ende -->
    <td><%#= link_to "Add Friend", friendships_path(:friend_id => user), :method => :post %>  </td>

    <!--
    <td><%#= user.persistence_token %></td>
    <td><%#= user.crypted_password %></td>
    <td><%#= user.password_salt %></td>
    <td><%#= user.single_access_token %></td>
    <td><%#= user.perishable_token %></td>
    <td><%#= user.login_count %></td>
    <td><%#= user.failed_login_count %></td>
    <td><%#= user.last_request_at %></td>
    <td><%#= user.current_login_at %></td>
    <td><%#= user.last_login_at %></td>
    <td><%#= user.current_login_ip %></td>
    <td><%#= user.last_login_ip %></td>     -->


  </tbody>
<% end %>
</table>


 <!--ADMINFIELD-->
        <%# if current_user.admin? %>
            <%#= link_to 'New User', new_user_path %>
        <%# end %>
    <%# end %>

     <!-- Adminfield ende -->

app/views/users/new.html.erb
    <h1>Register</h1>

        <%= render 'form' %>
        <script type="text/javascript" >validateForm("new_user")</script>

app/views/users/show.html.erb
    <h1><%= current_user.login %>'s Account</h1>

    <div class="field">

    <label class='label'>Username</label>
    <input type=text class="textarea" value="<%= @user.login%>" disabled="disabled"/>
    <label class="label">Email</label>
    <input type=text class="textarea" value="<%= @user.email %>" disabled="disabled"/>
  </div>

  <div >
    <%= link_to '', edit_user_path(@user), :class=>"button useredit", :title=>"Edit Account" %>

  </div>

  <!-- Friends -->

    <h2>Your Friends</h2>

    <ul>
      <% for friendship in @user.friendships %>
      <li>
        <%= h friendship.friend.login %>
        (<%= link_to "", friendship,  :method => :delete, confirm: 'Your are about to delete a friendship! Are you sure?',  class: 'button right delete', title: 'Delete Friend' %>)
      </li>
      <% end %>
    </ul>
    <p><%= link_to "Find Friends", friendships_path %></p>