config/routes.rb
Terminplaner::Application.routes.draw do

  resources :groups
  resources :user_sessions
  resources :users
  resources :user, :as => :friend
  resources :application
  resources :appointments
  resources :appointments, :collection => {:with_code => :get}
  resources :friendships
  resources :friendship_appointments
  resources :password_resets

  match 'signup' => 'users#new', :as => :signup
  match 'appointments#index' => "application", :action=>"set_layout", :mobile=>"1"
  match 'appointments#index' => "application", :action=>"set_layout", :mobile=>"0"
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout

  match 'appointments#index' => "application", :action=>"groups#edit"

  match ':controller(/:id(.:format)(/:action))'
  match ':controller(/:action(/:id(.:format)))'
  match ':controller(/:action(.:format))'
  match 'activate(/:activation_code)' => 'users#activate', :as => :activate_account
  match 'send_activation(/:user_id)' => 'users#send_activation', :as => :send_activation
  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  get "home/index"

  root :to => 'appointments#index'

end

app/models/friendship_appointment.rb
class FriendshipAppointment < ActiveRecord::Base
  belongs_to :user         , :class_name => 'User', :foreign_key =>'user_id'
  belongs_to :shared_friend, :class_name => 'User', :foreign_key =>'shared_friend_id'
  belongs_to :appointment
end

app/controllers/friendship_appointments_controller.rb
class FriendshipAppointmentsController < ApplicationController
  # GET /friendship_appointments
  # GET /friendship_appointments.json
  def index
    @groups = Group.all
    @group = Group.new
    @groups = Group.find(:all, :conditions => {:user_id => current_user})

    @friendship_appointments = FriendshipAppointment.all
    @users= User.all
       # @user = User.find(params[:user_id])


    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @friendship_appointments }
    end
  end

  # GET /friendship_appointments/1
  # GET /friendship_appointments/1.json
  def show
   # redirect_to user_path(current_user)
   # @friendship1 = Friendship.find(params[:id])
    @shared_friend = User.find(params[:id])
    @users = User.all
   # ###### redirect to appointments      ######
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @friendship_appointment }
    end
  end

  # GET /friendship_appointments/new
  # GET /friendship_appointments/new.json
  def new
    @friendship1 = Friendship.new
    @friendship2 = Friendship.new
  end

  # GET /friendship_appointments/1/edit
  def edit
    @friendship_appointment = FriendshipAppointment.find(params[:id])
  end


  # POST /friendship_appointments
  # POST /friendship_appointments.json
  def create

    @user = User.find(current_user)
    @appointment = Appointment.find(current_appointment)
       @shared_friend = User.find(params[:shared_friend_id])
       params[:friendship1] = {:user_id => current_user.id, :shared_friend_id => @shared_friend.id,:appointment_id => @appointment.id}
       params[:friendship2] = {:user_id => @shared_friend.id, :shared_friend_id => current_user.id,:appointment_id => @appointment.id,}
       @friendship1 = Friendship.create(params[:friendship1])
       @friendship2 = Friendship.create(params[:friendship2])


    if @friendship1.save && @friendship2.save
      flash[:notice] = "You shared your appointment with " + @shared_friend.login + "."
      #redirect_to appointments_path
    else
      flash[:error] = "Unable to share your appointment with " + @shared_friend.login + "."
      #redirect_to appointments_path
    end

  end

  # PUT /friendship_appointments/1
  # PUT /friendship_appointments/1.json
  def update

    @user = User.find(current_user)
    @shared_friend = User.find(params[:id])
    params[:friendship1] = {:user_id => @user.id, :shared_friend_id => @shared_friend.id}
    params[:friendship2] = {:user_id => @shared_friend.id, :shared_friend_id => @user.id}
    @friendship1 = Friendship.find_by_user_id_and_friend_id(@user.id, @shared_friend.id)
    @friendship2 = Friendship.find_by_user_id_and_friend_id(@shared_friend.id, @user.id)

    if @friendship1.update_attributes(params[:friendship1]) && @friendship2.update_attributes(params[:friendship2])
      flash[:notice] = "You shared your appointment with " + @shared_friend.login + "."
      redirect_to appointments_path
    else
      redirect_to appointments_path
    end
  end

  # DELETE /friendship_appointments/1
  # DELETE /friendship_appointments/1.json
  def destroy

    @user = User.find(current_user)
    @shared_friend = User.find(params[:id])
    @friendship1 = @user.friendships.find_by_friend_id(params[:id]).destroy
    @friendship2 = @shared_friend.friendships.find_by_user_id(params[:id]).destroy
    redirect_to appointments_path

  end

end

app/helpers/friendship_appointments_helper.rb
module FriendshipAppointmentsHelper
end

app/views/friendship_appointments/_form.html.erb
<%= form_for(@friendship_appointment) do |f| %>


  <div class="field">
    <%= f.label :user_id %>
    <%= f.number_field :user_id %>

    <%= f.label :appointment_id %>
    <%= f.number_field :appointment_id %>

    <%= f.label :shared_friend_id %>
    <%= f.number_field :shared_friend_id %>
    <span class="floatright">
        <%= f.submit '', :action => :new, :class=> 'button create', :title=>'Save Friend' %>
    </span>
  </div>
<% end %>

app/views/friendship_appointments/index.html.erb
<h1>Listing friendship_appointments</h1>

<table>
  <tr>
    <th>User_id</th>
    <th>Appointment_id</th>
    <th>Friend_Id</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @friendship_appointments.each do |friendship_appointment| %>
  <tr>
    <td><%=friendship_appointment.user_id %></td>
    <td><%=friendship_appointment.appointment_id %></td>
    <td><%=friendship_appointment.shared_friend_id %></td>
    <td><%= link_to 'Show', friendship_appointment %></td>
    <td><%= link_to 'Edit', edit_friendship_appointment_path(friendship_appointment) %></td>
    <td><%= link_to 'Destroy', friendship_appointment_path(:user_id => current_user, :id => friendship_appointment.shared_friend_id), confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>