config/routes.rb
Terminplaner::Application.routes.draw do

  resources :groups
  resources :user_sessions
  resources :users
  resources :user, :as => :friend
  resources :application
  resources :appointments
  resources :appointments, :collection => {:with_code => :get}
  resources :friendships
  resources :friendship_appointments
  resources :password_resets

  match 'signup' => 'users#new', :as => :signup
  match 'appointments#index' => "application", :action=>"set_layout", :mobile=>"1"
  match 'appointments#index' => "application", :action=>"set_layout", :mobile=>"0"
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout

  match 'appointments#index' => "application", :action=>"groups#edit"

  match ':controller(/:id(.:format)(/:action))'
  match ':controller(/:action(/:id(.:format)))'
  match ':controller(/:action(.:format))'
  match 'activate(/:activation_code)' => 'users#activate', :as => :activate_account
  match 'send_activation(/:user_id)' => 'users#send_activation', :as => :send_activation
  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  get "home/index"

  root :to => 'appointments#index'

end

app/views/header/_nav.html.erb
<header>
  <% if not current_page? :controller => 'calendar', :action => 'index' %>
  <div id="navbar">

    <div class="navleft">
      <ul>
       <% if current_user %>
          <li><h1><%= link_to "#{current_user.login}s Yagenda", appointments_path, :class => "title" %></h1></li>
       <% else %>
          <li><h1>YAGENDA</h1></li>
       <% end %>
      </ul>
    </div>
    <div class="navright">

        <% if current_user %>

            <% if current_user.admin? %>
              <%= link_to '',  users_path, :class=> 'button users', :alt => 'Users', :title => 'Users' %>
            <% end %>
            <a id="btSettings" class='button settings left' href="#" title="Settings"></a>
            <%= link_to '', :logout, :class=> 'button logout right', :alt => 'Logout', :title => 'Logout'%>
        <% else %>
        <% end %>
    </div>
  </div>

  <%= render :partial => "header/settings" %>


   <% end %>
</header>

app/views/header/_settings.html.erb
   <% if current_user %>
    <div id="Settings">
      <div class="field">
        <h4>Profile</h4>
        <%= render :partial => 'users/edituser', :locals => {:meinevariable => current_user} %>
      </div>

      <div class="field">
        <h4>Groups</h4>
        <% @groups.each do |group| %>
            <% unless group.id == 1 %>
                <%= render :partial => 'groups/editallgroups', :locals => {:meinevariable => group} %>

            <% end %>
        <% end %>
	    <%= render :partial => "groups/form" %>
        <script type="text/javascript" >validateForm("new_group")</script>
      </div>
      <div class="field">
        <h4>Friends</h4>
        <%= render :partial => 'friendships/editfriendships' %>
      </div>
   </div>
   <% end %>